### ISSUE TITLE
W9 Gem lightning talk topics

### ISSUE THREAD

**Issue by nathanallen** [sf-wdi-25/notes#62]
####Active Record Plugins
* **Active Record Nesting**: Awesome nested set | Ancestry | Acts as tree | Closure Tree | Better nested set
* **Active Record Soft Delete**: rails3_acts_as_paranoid | paranoia | Acts as paranoid | Acts as archive | Permanent records
* **Active Record Sortables**: Acts as list | ranked-model | Sortable | Resort
* **Active Record User Stamping**: Userstamp | User stamp | Acts as audited | Record activities | Acts as loggable
* **Pagination**: will_paginate | Kaminari | sorted | ajax_pagination | Paged scopes
* **Rails Comments**: juvia | Acts as commentable with threading | Acts as commentable | Disqus | opinio
* **Rails DB Bootstrapping**: Seed-fu | Populator | seedbank | Bootstrapper | Db-populate
* **Rails Ratings**: Ajaxful-rating | ajaxful_rating | letsrate | Acts as rateable | mongoid_rateable
* **Rails Search**: Sunspot | sunspot_rails | Tire | Thinking-sphinx | Rsolr
* **Rails Tagging**: Acts-as-taggable-on | Is taggable | rocket_tag | Acts as taggable redux | Acts as taggable on steroids

####Background Processing
* **Background Jobs**: Resque | Delayed job | sidekiq | Bunny | Beanstalkd
* **Scheduling**: Whenever | resque-scheduler | Rufus-scheduler | Clockwork | Craken

####Code Quality
* **Code Metrics**: SimpleCov | Rails best practices | Rcov | rubocop | Cane

####Communication
* **Asynchronous E-Mail**: Resque Mailer | Mail queue | Mailhopper | Resque Mail Queue
* **CRM Apps**: Fat free crm | Mongo crm | railscrm | myitcrm2 | Cohort
* **E-Mail Preview**: Letter Opener | MailCatcher | mail_view | Rails Email Preview | sanitize_email
* **E-Mail Processing**: Mailman | Fetcher | griddler | newman | Mail fetcher
* **E-Mail Sending**: Action Mailer | Mail | Pony | Tmail | capistrano_mailer
* **Forum Systems**: forem | Altered beast | thredded | forum_monster
* **Inline CSS for E-Mail**: premailer | Roadie | mail_style | inline-style | premailer-rails3

####Content Management & Blogging
* **Blog Engines**: Octopress | Publify | Toto | blogit | Serious
* **Content Management**: Refinery CMS | BrowserCMS | Locomotive | Radiant | Comfortable Mexican Sofa
* **Static Website Generation**: Jekyll | Middleman | high_voltage | Nanoc | stasis
* **Wiki Apps**: Gollum | Git-wiki | Instiki | irwi | Olelo

####CSS
* **CSS with Ruby**: Sass | Compass | sass-rails | bootstrap-sass | twitter-bootstrap-rails
* **Font-Face Servers**: Fontue | Fistface

####Data Persistence
* **CSV Parsers**: FasterCSV | smarter_csv | postgres-copy | ccsv | csv_pirate
* **Redis Clients**: Redis Ruby | Redis Store | Redis Objects | Ohm | redis_orm

####Developer Tools
* **Benchmarking**: method_profiler | rbench | bench_press | better-benchmark | Tach
* **CLI Option Parsers**: highline | Slop | cocaine | mixlib-cli | Trollop
* **Configuration Management**: dotenv | settingslogic | Figaro | dotenv-rails | configuration
* **git Tools**: Grit | githug | Ruby/Git | rugged | gitolite
* **irb Tools**: Dotfiles | Awesome print | Hirb | wirble | pry-rails

####Documentation Tools
* **Documentation Generators**: RDoc | Yard | Sdoc | DocumentUp | Rocco
* **Gem Doc Viewers**: Bdoc | Sinatra-rubygems | Docbox

####Documents & Reports
* **PDF Generation**: Prawn | Pdfkit | Wicked pdf | Wkhtmltopdf | Prawnto
* **PDF Processing**: pdf-reader | pdf_info
* **Reports & Spreadsheets**: spreadsheet | axlsx | roo | Ruport | google-spreadsheet-ruby

####E-Commerce and Payments
* **Online Shops**: Spree | RoR eCommerce | Invoicing | Shippinglogic | nimbleshop
* **Payments**: Active Merchant | braintree | Stripe | paypal_adaptive | paypal-express
* **Subscription Management**: Freemium | jackpot | fastspring-saasy | SubscriptionFu

####Graphics
* **Graphing**: Lazy high charts | Googlecharts | Gruff | Open flash chart | Tufte-graph
* **Image Processing**: chunky_png | RMagick | MiniMagick | Image science | image_sorcery
* **QR Codes**: rqrcode | rqrcode-rails3 | rqrcode_png | zxing | zbar
* **Visualizing Data**: Raphael | ruby-graphviz

####HTML & Markup
* **Breadcrumb Builders**: breadcrumbs_on_rails | crummy | gretel | breadcrumbs | ariane
* **Form Builders**: Simple Form | Formtastic | nested_form | cocoon | twitter_bootstrap_form_for
* **Markup processors**: Markup | Redcarpet | RedCloth | vkhater-redcarpet | Rdiscount
* **Microformats**: Mofo | Microformats helper | Prism
* **Rails Menu Builders**: Simple-navigation | tabs_on_rails | Semantic-menu | Navigasmic | active_link_to
* **Rails Wizards**: Wicked | Actsaswizard | Wizardly | Wizard | Partially valid
* **Syntax Highlighting**: coderay | rouge | Albino | Jquery-syntax | Harsh
* **Table Builders**: datagrid | wice_grid | tabletastic | table_cloth | table_for_collection
* **Template Engines**: erubis | Tilt | Haml | Slim | Liquid

####JavaScript
* **JavaScript Tools**: Uglifier | coffee-script | gon | opal

####Maintenance & Monitoring
* **App Instrumentation**: New Relic RPM | dashing | better_errors | fnordmetric | bullet
* **Exception Notification**: Errbit | Airbrake | Exception notification | Exceptional | Honeybadger
* **Log Analysis**: logstash | Graylog2 | request-log-analyzer | central_logger | ntail
* **Logging**: log4r | Logging | gelf | yell | mongodb_logger
* **Server Monitoring**: God | Bluepill | amon | sensu | Outpost

####Package & Dependency Management
* **Bundler Tools**: rubygems-bundler | Appraisal | guard-bundler | spitball | noexec
* **Dependency Management**: Bundler | berkshelf | librarian | Braid | Isolate
* **Gem Hosting**: geminabox | stickler
* **Packaging Systems**: Rubygems | Rip | Rpg | Coral
* **Packaging to Executables**: Ocra | releasy | Crate

####Provision, Deploy & Host
* **Continuous Integration**: Travis | Cruisecontrol.rb | Cijoe | Jenkins.rb | Integrity
* **Deployment Automation**: Capistrano | Heroku | mina | Moonshine | git-deploy
* **Web servers**: Thin | Unicorn | Passenger | Puma | Pow

####Rails Plugins
* **Rails Activity Feeds**: public_activity | TimelineFu | Pfeed | streama | unread
* **Rails Admin Interfaces**: ActiveAdmin | Rails Admin | ActiveScaffold | Typus | Streamlined
* **Rails App Templates**: rails3-application-templates | rails_apps_composer | Rails-templates | Suspenders | Bigoldrailstemplate
* **Rails File Uploads**: Paperclip | Carrierwave | Attachment fu | Dragonfly | Imagery
* **Rails Permalinks & Slugs**: FriendlyId | Stringex | Babosa | Permalink fu | ObfuscateId
* **Rails Presenters**: Draper | Cells | Apotomo | Active presenter | ActiveDecorator
* **Rails Subdomains**: Subdomain-fu | Subdomain routes | Subdomain account | Sso what
* **Recommendation Engines**: recommendify | recommendable | coletivo | Slope One
* **Reputation Engines**: activerecord-reputation-system | merit | honor | recognition
* **User Messaging Systems**: mailboxer | rails-messaging | acts-as-messageable | maktoub | inboxes

####Security
* **Encryption**: Attr encrypted | Strongbox | crypt_keeper | symmetric-encryption | Sentry
* **Rails Authentication**: Devise | OmniAuth | Authlogic | Restful-authentication | Sorcery
* **Rails Authorization**: Cancan | Declarative authorization | rolify | pundit | Acl9
* **Rails Captcha**: Recaptcha | Negative-captcha | Simple-captcha-mirror | galetahub-simple_captcha | humanizer
* **Security Tools**: brakeman | Loofah | Tarantula | Xss terminate | Rails xss
* **Spam Detection**: Rakismet | Defender | Defensio-ruby | Akismetor | Rdefensio

####Testing
* **A/B Testing**: Vanity | Split | seven_minute_abs | bandit | ABingo

####Time & Space
* **Calendars**: Event calendar | ri_cal | Calendar helper | icalendar | Weekly builder
* **Geocoding & Maps**: Geocoder | Geokit | gmaps4rails | RGeo | Geokit-rails
* **I18n**: I18n | i18n-js | R18n | http_accept_language | Translate routes
* **Natural Language Date Parsing**: Chronic | Chronic Duration | Nickel | Tickle | kronic
* **Recurring Events**: Ice cube | Recurrence | Schedule fu | Runt | Recurring event

####Web Apps, Services & Interaction
* **API Builders**: Grape | rabl | jbuilder | active_model_serializers | acts_as_api
* **API Clients**: Twitter | koala | fb_graph | Linkedin | youtube_it
* **Atom & RSS Feed Parsing**: Feedzirra | Simple-rss | Feed-normalizer | ratom | rfeedparser
* **HTML parsing**: Nokogiri | Hpricot | Libxml-ruby | Scrubyt | Scrapi
* **HTTP clients**: Rest-client | Httparty | faraday | multipart-post | Excon
* **JSON Parsers**: json | multi_json | yajl-ruby | json pure | crack
* **URL Rewriting**: rack-rewrite | Refraction | redirect
* **User Agent Detection**: useragent | browser | mobylette | agent_orange | user-agent
* **Web Analytics**: gattica | gabba | rack-google-analytics | Garb | google-analytics-rails
* **Web App Frameworks**: Sinatra | Padrino | Cramp
* **Web Content Scrapers**: Pismo | data_miner | metainspector | cobweb | sinew

**Comment by tgaff** [comment]
Gem lists:
https://github.com/markets/awesome-ruby
http://code.tutsplus.com/articles/24-extremely-useful-ruby-gems-for-web-development--net-23863

**Comment by nathanallen** [comment]
Created here: https://gist.github.com/nathanallen/c491bde4d07b9a96fceb
