### ISSUE TITLE
Empty link & small typo

### ISSUE THREAD

**Issue by anonym0us3** [sf-wdi-25/notes#66]
Line 310: https://github.com/sf-wdi-25/notes/blame/master/week-08-vagabond/homework/README.md#L310

Fixed typo, added link (to be fair, you guys *did* already provide us with the link earlier in the file):

First [install it](https://github.com/thoughtbot/factory_girl_rails).

Edit: couldn't figure out how to prevent github from autoparsing the markdown styling

**Comment by tgaff** [comment]
@anonym0us3 thanks, fixed.  
BTW, there's no actual assignment here aside from reading.  You don't need to follow the steps, just read them.
